apiVersion: apps/v1
kind: Deployment
metadata:
  name: awaken-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awaken-prod
  template:
    metadata:
      labels:
        app: awaken-prod
    spec:
      containers:
      - name: awaken-prod
        image: gcr.io/kuar-demo/kuard-amd64:blue
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
