apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    name: test
spec:
  containers:
  - name: test
    image: gcr.io/kuar-demo/kuard-amd64:blue
    resources:
      requests: 
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "256Mi"
        cpu: "1000m"
    ports:
      - containerPort: 5600
        name: http
        protocol: TCP
